# Generated by Django 2.2.9 on 2020-05-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('credential_id', models.TextField(blank=True, null=True)),
                ('body', models.TextField()),
                ('completion_date', models.DateField()),
            ],
        ),
    ]
