# Generated by Django 2.2.9 on 2020-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
