# Generated by Django 2.2.9 on 2020-04-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_achievements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
