# Generated by Django 2.2.9 on 2020-04-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='urls',
            field=models.TextField(null=True),
        ),
    ]
