# Generated by Django 2.2.9 on 2020-04-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dtl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
